### ISSUE TITLE
UnimplementedError

### ISSUE THREAD

**Issue by bonifacemacara** [hrvojecukman/image_downloader_web#3]
```
[ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: UnimplementedError
#0      CanvasElement.context2D (package:universal_html/src/html/dom/element_subclasses.dart:380:51)
#1      CanvasElement.context2D (package:universal_html/src/html/dom/element_subclasses.dart)
#2      WebImageDownloader.downloadImageFromUInt8List (package:image_downloader_web/src/web_image_downloader.dart:44:24)
```

**Comment by hrvojecukman** [comment]
Can you please provide more info because I couldn't reproduce the error. Which platform were you using?

**Comment by gfasidis** [comment]
Hello I have the same error in MacOS Platform (arm edition)

Error log:

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: UnimplementedError
#0      CanvasElement.context2D (package:universal_html/src/html/dom/element_subclasses.dart:380:51)
#1      CanvasElement.context2D (package:universal_html/src/html/dom/element_subclasses.dart)
#2      WebImageDownloader.downloadImageFromUInt8List (package:image_downloader_web/src/web_image_downloader.dart:44:24)
<asynchronous suspension>
#3      WebImageDownloader.downloadImageFromWeb (package:image_downloader_web/src/web_image_downloader.dart:21:7)
<asynchronous suspension>
#4      _ServiceDataActivityState.saveImage (package:aesthetic_center_crm/Activities/service_data_activity.dart:125:7)
<asynchronous suspension>

Code:
if(kIsWeb || **Platform.isMacOS**) {
      await WebImageDownloader().downloadImageFromWeb(urlPhoto,name: "appointmentPhoto").then((value) {
        Navigator.pop(dialogIndicatorContext!);
        ScaffoldMessenger.of(context).showSnackBar(
            const SnackBar(content: Text("Done!")));
      },);
    }

**Comment by hrvojecukman** [comment]
Sorry for the inconvenience but this package is only for Flutter Web. In the Readme.MD the first sentence says: `Download images from URL on Flutter Web` but I am open to any suggestions to be more clear about its usage. All the help on how the Readme or the package could be improved would be appreciated

**Comment by gfasidis** [comment]
Don't worry. I miss understand with pub.dev site where your package also has compatibility with Mac OS. So I assume that you forget to update the readme file
<img width="583" alt="Στιγμιότυπο 2022-12-30, 13 10 54" src="https://user-images.githubusercontent.com/28733848/210064235-a825fc62-3775-4c1e-a922-d6f108c71fed.png">

I want to ask another question off topic maybe but from web in mobile I can't download the image...
